### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by mjkmoynihan** [tofis/human4d_dataset#1]
This dataset looks great and the analysis provided in the paper is really thorough and impressive! 
Is it available yet? It seems to be hosted on IEEEDataport but I can't access any data?

**Comment by tofis** [comment]
Hello @mjkmoynihan, apologize for the late reply. The biggest part of the dataset is already publicly available at ZENODO. You can find the corresponding URLs in parts to the updated readme as well, however I place them here for quick access.

https://zenodo.org/record/4473009#.YH6nvOgzaUk 
https://zenodo.org/record/4473047#.YH6n1egzaUk 
https://zenodo.org/record/4483817#.YH6n5OgzaUk 
https://zenodo.org/record/4484110#.YH6n-ugzaUk 

Let me know in the case you need further support.
